GaleriaArte-mvc/Controllers/HomeController.cs
using System.Diagnostics;
using GaleriaArte_mvc.Data;
using GaleriaArte_mvc.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace GaleriaArte_mvc.Controllers
{
    public class HomeController : Controller
    {
        private readonly GaleriaDbContext _context;
        
        public HomeController(GaleriaDbContext context)
        {
            _context = context;
        }


        public async Task<IActionResult> Index()
        {
            var obras = await _context.Obras
                .Take(6).Include(o => o.Artista)
                .ToListAsync();
            return View(obras);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

GaleriaArte-mvc/Controllers/ObraController.cs
using GaleriaArte_mvc.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace GaleriaArte_mvc.Controllers
{
    public class ObraController : Controller
    {
        private GaleriaDbContext _context;
        public ObraController(GaleriaDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> DetalleObra(string id)
        {
            var obra = await _context.Obras.FirstOrDefaultAsync(o => o.Id.ToString() == id);
            return View(obra);
        }
    }
}

GaleriaArte-mvc/Views/Home/Index.cshtml
@model List<Obra>

@{
    ViewData["Title"] = "Galeria Arte";
}


<h1>Galeria de Arte</h1>
<div class="row row-cols-1 row-cols-md-3 g-4">
    @foreach (var item in Model)
    {
        <div class="col">
            <div class="card" style="height: 400px">
                <img src="@item.UrlImagen" class="card-img-top img-fluid h-50 object-fit-cover" alt="">
                <div class="card-body">
                    <h5 class="card-title">@item.Titulo</h5>
                    <p class="card-text">Artista: @item.Artista.Nombre</p>
                    <a asp-controller="Obra" asp-action="DetalleObra" asp-route-id="@item.Id">Ver Detalle</a>
                </div>
            </div>
        </div>
    }

</div>